spring.application.name=demo
server.port=9090

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/demoDb?createDatabaseIfNotExist=true
#spring.datasource.url=jdbc:mysql://mysql-docker:3308/demoDb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Chamod@100
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true


## MongoDB connection settings
#spring.data.mongodb.host=10.41.162.125
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=demoDb
#spring.data.mongodb.username=chamodsapumal007
#spring.data.mongodb.password=dKON1ZtIQ1wGWY1z
