version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Chamod@100
      MYSQL_DATABASE: demoDb
      MYSQL_USER: Sapumal
      MYSQL_PASSWORD: Chamod@100
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-mysql-network

  spring-app:
    build: .
    container_name: spring-boot-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/your_database_name
      SPRING_DATASOURCE_USERNAME: Sapumal
      SPRING_DATASOURCE_PASSWORD: Chamod@100
    ports:
      - "9090:9090"
    networks:
      - spring-mysql-network

volumes:
  mysql_data:

networks:
  spring-mysql-network:
    driver: bridge